server:
  port: 8088
  max-http-header-size: 20MB
  tomcat:
    uri-encoding: UTF-8
spring:
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/drug_information?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 25
      auto-commit: true
      idle-timeout: 30000
      pool-name: ExpendHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-init-sql: SELECT 1
  ### 时间返回格式处理
  jackson:
    date-format: yyyy-MM-dd HH:mm:s
    time-zone: GMT+8
    #设置
  resources:
    static-locations: classpath:/static/,classpath:/templates/




## mybatis扫描
mybatis:
  mapperLocations: classpath:/mapper/*.xml
  global-config:
    db-config:
      db-type: mysql



#日志
#是否开启日志
debug: true
#logging.level.* 来具体输出哪些包的日志级别
logging:
  level:
    root: debug
    org:
      springframework:
        web: debug
    com:
      ruantian:
        controller: debug









